package sqliterefdriver

// autogenerated with github.com/hackborn/tox
// do not modify

const (
	_refKeysVar        = "$KEYS$"
	_refKeyValuesVar   = "$KEYVALUES$"
	_refFieldsVar      = "$FIELDS$"
	_refTableVar       = "$TABLE$"
	_refValuesVar      = "$VALUES$"
	_refFieldValuesVar = "$FIELDVALUES$"

	_refAndKeyword      = "AND"
	_refAndKeywordWS    = " AND "
	_refEqualsKeyword   = "="
	_refEqualsKeywordWS = " = "

	_refQuoteSz = string(rune('\''))

	_refSetSql = `INSERT INTO $TABLE$ ($FIELDS$) VALUES($VALUES$) ON CONFLICT($KEYS$) DO UPDATE SET $FIELDVALUES$;`
	_refDelSql = `DELETE FROM $TABLE$ WHERE ($KEYVALUES$);`
)

var (
	_refDefinitions = map[string]string{
		// Begin tabledefs
		`Company`: `DROP TABLE IF EXISTS Company;
CREATE TABLE IF NOT EXISTS Company (
	id VARCHAR(255),
	name VARCHAR(255),
	val INTEGER,
	fy INTEGER,
	PRIMARY KEY (id)
);`,
		`Filing`: `DROP TABLE IF EXISTS Filing;
CREATE TABLE IF NOT EXISTS Filing (
	ticker VARCHAR(255),
	end VARCHAR(255),
	form VARCHAR(255),
	val INTEGER,
	units VARCHAR(255),
	fy INTEGER,
	PRIMARY KEY (ticker, end, form)
);`,
		// End tabledefs
	}
)
